# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.lolapi:
        class:        AppBundle\Services\LoLAPI\LoLAPIService
        arguments:    ['@service_container']
    app.lolsummoner:
        class:        AppBundle\Services\SummonerService
        arguments:    ['@service_container','@app.lolapi']
    app.staticdataupdate:
        class:        AppBundle\Services\StaticDataUpdateService
        arguments:    ['@service_container','@app.lolapi']
    app.interceptor.action_listener:
        class: AppBundle\EventListener\InterceptorListener
        arguments: ['@twig']
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
    app.authentication_handler:
        class:        AppBundle\Handler\AuthenticationHandler
        arguments:    ['@service_container']
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        arguments: [ "@service_container" ]
        tags:
            - { name: twig.extension }