# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.lolapi:
        class:        AppBundle\Services\LoLAPI\LoLAPIService
        arguments:    ['%riot_api_key%']
    app.lolsummoner:
        class:        AppBundle\Services\SummonerService
        arguments:    ['@logger', '@doctrine.orm.entity_manager', '@app.lolapi', '%current_season%']
    app.staticdataupdate:
        class:        AppBundle\Services\StaticDataUpdateService
        arguments:    ['@doctrine','@app.lolapi']
    app.interceptor.action_listener:
        class: AppBundle\EventListener\InterceptorListener
        arguments: ['@twig', '%static_data_version%']
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
    app.authentication_handler:
        class:        AppBundle\Handler\AuthenticationHandler
        arguments:    ['@translator.default']
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        arguments: ['@logger', '%static_data_version%']
        tags:
            - { name: twig.extension }