# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.lolapi:
        class:        AppBundle\Services\LoLAPI\LoLAPIService
        arguments:    ['@service_container']
    app.lolsummoner:
        class:        AppBundle\Services\SummonerService
        arguments:    ['@service_container','@app.lolapi']
    app.staticdataupdate:
        class:        AppBundle\Services\StaticDataUpdateService
        arguments:    ['@service_container','@app.lolapi']
