app_dev_test:
    path:     /test
    defaults: { _controller: AppBundle:StaticData:updateChampions }
    methods:  [GET]

app_dev_featured:
    path:     /featured
    defaults: { _controller: AppBundle:Dev:featured }
    methods:  [GET]

app_dev_monitoring:
    path:     /monitoring
    defaults: { _controller: AppBundle:Dev:monitoring }
    methods:  [GET]

app_dev_monitoring_ajax:
    path:     /monitoringAjax
    defaults: { _controller: AppBundle:Dev:monitoringAjax }

app_summoner_history_ajax:
    path:     /summoner/{region}/{summonerId}/historyAjax
    defaults: { _controller: AppBundle:SummonerAjax:history }