app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Static:homepage }
    methods:  [GET]

app_searchbar:
    path:     /search
    defaults: { _controller: AppBundle:Static:searchbar }
    methods:  [POST]

app_champion_mastery_summoner:
    path:     /championmastery/{region}/{summonerId}
    defaults: { _controller: AppBundle:ChampionMastery:summoner }
    methods:  [GET]

app_about:
    path:     /about
    defaults: { _controller: AppBundle:Static:about }
    methods:  [GET]

app_users:
    path:     /users
    defaults: { _controller: AppBundle:Static:about }
    methods:  [GET]

app_profile:
    path:     /profile/{userId}
    defaults: { _controller: AppBundle:LoLAPI:profile }
    methods:  [GET]

app_profile_edit:
    path:     /profile/{userId}/edit
    defaults: { _controller: AppBundle:LoLAPI:editProfile }
    methods:  [GET]

app_link_summoner_to_user_blank:
    path:     /link-account
    defaults: { _controller: AppBundle:SummonerAjax:linkSummonerToUserBlank }
    methods:  [POST]
    requirements: { method: POST }

app_link_summoner_to_user:
    path:     /link-account/{summonerName}
    defaults: { _controller: AppBundle:SummonerAjax:linkSummonerToUser }
    methods:  [POST]
    requirements: { method: POST }

app_update_summoner_infos:
    path:     /summoner/{region}/{summonerId}/update
    defaults: { _controller: AppBundle:SummonerAjax:updateInfos }
    methods:  [POST]
    requirements: { method: POST }

app_summoner:
    path:     /summoner/{region}/{summonerId}
    defaults: { _controller: AppBundle:Summoner:index }
    methods:  [GET]

app_summoner_chests:
    path:     /summoner/{region}/{summonerId}/chests
    defaults: { _controller: AppBundle:Summoner:chests }
    methods:  [POST]
    requirements: { method: POST }

app_summoner_chests_ajax:
    path:     /summoner/{region}/{summonerId}/chestsAjax
    defaults: { _controller: AppBundle:SummonerAjax:chests }
    methods:  [POST]
    requirements: { method: POST }

app_summoner_champion_masteries_ajax:
    path:     /summoner/{region}/{summonerId}/championMasteriesAjax
    defaults: { _controller: AppBundle:SummonerAjax:championMasteries }
    methods:  [POST]
    requirements: { method: POST }

app_summoner_runes_ajax:
    path:     /summoner/{region}/{summonerId}/runesAjax
    defaults: { _controller: AppBundle:SummonerAjax:runes }
    methods:  [POST]
    requirements: { method: POST }

app_summoner_live_game_ajax:
    path:     /summoner/{region}/{summonerId}/liveGameAjax
    defaults: { _controller: AppBundle:SummonerAjax:liveGame }
    methods:  [POST]
    requirements: { method: POST }

app_dev_test:
    path:     /test
    defaults: { _controller: AppBundle:StaticData:updateChampions }
    methods:  [GET]

app_admin_update_champions:
    path:     /update/champions
    defaults: { _controller: AppBundle:Admin:updateChampions }
    methods:  [GET]

app_admin_update_runes:
    path:     /update/runes
    defaults: { _controller: AppBundle:Admin:updateRunes }
    methods:  [GET]

app_admin_update_masteries:
    path:     /update/masteries
    defaults: { _controller: AppBundle:Admin:updateMasteries }
    methods:  [GET]

app_summoner_create_ajax:
    path:     /summoner/{region}/{summonerId}/create
    defaults: { _controller: AppBundle:Summoner:ajaxCreate }
    methods:  [POST]
    requirements: { method: POST }
